version: '3'
services:
  composer:
    image: composer:1.9.3
    environment:
      - COMPOSER_CACHE_DIR=/design-pattern/.cache/composer
    volumes:
      - .:/app
    restart: always
  # NEW IN THIS SECTION!!!
  php:
    image: php:7.4-cli
    restart: always
    volumes:
      - .:/design-pattern
    working_dir: /design-pattern
  phpunit:
    image: php:7.4-cli
    restart: always
    volumes:
      - .:/design-pattern
    working_dir: /design-pattern
    entrypoint: vendor/bin/phpunit